CREATE TABLE IF NOT EXISTS map_units (
    map_unit_id integer,
    map_unit_name text,
    meadow text,
    conifer_phase text,
    indirect_benefits_area integer,
    notes text,
    map_unit_area real,
    spring_hsi real,
    summer_hsi real,
    winter_hsi real,
    pj_cover real,
    current_breed real,
    current_summer real,
    current_winter real,
    projected_breed real,
    projected_summer real,
    projected_winter real,
    no_transects integer
);