CREATE TABLE IF NOT EXISTS site_scale_values (
    map_unit_id integer,
    map_unit_name text,
    map_unit_area real,
    indirect_benefits text,
    desktop_transects integer,
    no_transects integer,
    meadow text,
    conifer_phase text,
    sage_species text,
    dist_sage real,
    b_sage_cover real,
    b_shrub_cover real,   
    b_grass_cover real,
    b_forb_cover real,
    b_forb_rich real,
    b_brotec_cover real,
    s_forb_cover real,
    s_forb_rich real,
    s_grass_cover real,
    s_brotec_cover real,
    s_dist_sage real,
    w_sage_height real,
    w_sage_cover real
);