CREATE TABLE IF NOT EXISTS scoring_curves_v100 (
    attr_value integer,
    b_sage_cover real,
    b_shrub_cover real,
    b_forb_cover_arid real,
    b_forb_cover_mesic real,
    b_forb_rich_arid real,
    b_forb_rich_mesic real,
    s_forb_cover_arid real,
    s_forb_cover_mesic real,
    s_forb_cover_meadow real,
    s_forb_rich_arid real,
    s_forb_rich_mesic real,
    s_grass_cover_arid real,
    s_grass_cover_mesic real,
    s_grass_cover_meadow real,
    w_sage_height_big real,
    w_sage_height_low real,
    w_sage_cover_big real,
    w_sage_cover_low real,
    brotec_cover real,
    s_dist_sage_altered real,
    s_dist_sage_unaltered real
);