INSERT INTO scoring_curves_v100 (
    attr_value,
    b_sage_cover,
    b_shrub_cover,
    b_forb_cover_arid,
    b_forb_cover_mesic,
    b_forb_rich_arid,
    b_forb_rich_mesic,
    s_forb_cover_arid,
    s_forb_cover_mesic,
    s_forb_cover_meadow,
    s_forb_rich_arid,
    s_forb_rich_mesic,
    s_grass_cover_arid,
    s_grass_cover_mesic,
    s_grass_cover_meadow,
    w_sage_height_big,
    w_sage_height_low,
    w_sage_cover_big,
    w_sage_cover_low,
    brotec_cover,
    s_dist_sage_altered,
    s_dist_sage_unaltered)
    VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)