INSERT INTO site_scale_values(
    map_unit_id,
    map_unit_name,
    map_unit_area,
    indirect_benefits,
    desktop_transects,
    no_transects,
    meadow,
    conifer_phase,
    sage_species,
    dist_sage,
    b_sage_cover,
    b_shrub_cover,   
    b_grass_cover,
    b_forb_cover,
    b_forb_rich,
    b_brotec_cover,
    s_forb_cover,
    s_forb_rich,
    s_grass_cover,
    s_brotec_cover,
    s_dist_sage,
    w_sage_height,
    w_sage_cover)
    VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)